# This is a basic workflow to help you get started with Actions

name: pipeline

on:
 push:
  branches: [ main ]
  paths:
   - Chapter15/**
   - .github/workflows/pipeline.yamls
  workflow-dispatch:
   env:
    ACRNAME: handsonpipelinetcor
   jobs:
    CI:
     runs-on: ubuntu-latest
   steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: az CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ACR login
      run: az acr login -n $ACRNAME
    - name: build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./Chapter15
        push: true
        tags: ${{ env.ACRNAME }}.azurecr.io/website/website:${{ github.run_number }}
